### PR TITLE
librdkafka v1.9.1, but require curl even on Windows

### PR DESCRIPTION
**Pull request by lpsinger**
Perhaps the curl dependency is fixed on Windows in this version?

### CODE REVIEW

**Comment by lpsinger** [comment]
Still failing. @edenhill, would you please take a look?

**Comment by StephenSmith25** [comment]
I've asked here https://github.com/edenhill/librdkafka/discussions/3899 - I feel like a link to the curl libraries is missing for the CMake target, hence missing symbols. 

The Linux and mac builds use autotools, whereas the windows one uses CMake, which appears to be a community supported endeavor, so maybe something was overlooked.

**Comment by StephenSmith25** [comment]
@lpsinger I tested a CMake patch here https://github.com/conda-forge/librdkafka-feedstock/pull/77 - 
```
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 33b3ced1..31783569 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -200,6 +200,10 @@ if(WITH_HDRHISTOGRAM)
   target_link_libraries(rdkafka PUBLIC m)
 endif()
 
+if(WITH_CURL)
+    target_link_libraries(rdkafka PRIVATE ${CURL_LIBRARIES})
+endif()
+
 if(WITH_ZLIB)
   find_package(ZLIB REQUIRED)
   target_include_directories(rdkafka PRIVATE ${ZLIB_INCLUDE_DIRS})

```
Seems to all build okay, provided I've not done anything wrong - You could cherry-pick my commit and then we could merge this if you like. I guess I'll need to submit the fix upstream so at some point we can remove the patch.

**Comment by StephenSmith25** [comment]
Sure, that works as well, was just looking for another of set of eyes - I'll go ahead and close this and merge #77 then.

**Pull request closed without merging**
