### PR TITLE
Update to v2.2.0

### PR DESCRIPTION
**Pull request by r-owen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by r-owen** [comment]
<code>@<space/>conda-forge-admin, please rerender</code>

**Comment by StephenSmith25** [comment]
Thanks for this. It would seem that in v2.2.0 there is a new example added which explicitly includes `unistd.h` https://github.com/confluentinc/librdkafka/blob/master/examples/idempotent_producer.c.  I imagine this this is not available on windows, so we cannot build it. I feel like we have two potential solutions,

1) Disable the examples in CMake with `RDKAFKA_BUILD_EXAMPLES` (but I'm not sure if users of the library need these?)
2) Patch the CMake to disable this one example?

**Comment by r-owen** [comment]
Setting the env var seems simpler and safer, but I don't know if any users might care about the examples. I only use librdkafka for confluent_kafka, and I imagine that is the most common use case.

**Comment by r-owen** [comment]
I tried disabling building examples on Windows and now [tests fail](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=748417&view=logs&jobId=a70f640f-cc53-5cd3-6cdc-236a1aa90802&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f) but I can't tell what failed from the linked log.

**Comment by StephenSmith25** [comment]
I'm also not really sure what that log is showing. Personally, I would have updated the options in the `bld.bat` (rather than the meta.yaml) file https://github.com/conda-forge/librdkafka-feedstock/blob/main/recipe/bld.bat which is the file corresponding to the Windows build. In this file we can supply options to CMake

```
...
  -DWITH_SNAPPY=ON ^
  -DWITH_ZLIB=ON ^
  -DWITH_CURL=ON ^
  -DRDKAFKA_BUILD_EXAMPLES=OFF ^   <----- insert the new option
...
```

which should set the option in https://github.com/confluentinc/librdkafka/blob/efc65e776d85e60321950fb4e167d4e2c215f183/CMakeLists.txt#L183

**Comment by r-owen** [comment]
OK. I'll try disabling the examples the way you suggested. That does seem cleaner.

**Comment by r-owen** [comment]
That worked. So I think this is ready for review!

**Comment by StephenSmith25** [comment]
Thanks! I'll try keep an eye out as I'm sure we'll be able to re-enable those examples at some point. Seems like a bit of an oversight on their end.

**Pull request merged**
