### PR TITLE
Update recipe to version 0.9.5

### PR DESCRIPTION
**Pull request by rmax**

### CODE REVIEW

**Comment by rmax** [comment]
ping @kwilcox

**Comment by kwilcox** [comment]
Eep! Totally missed this. Most likely needs a rerender, no?

**Comment by rmax** [comment]
Rerender commit included.

**Comment by jakirkham** [comment]
The token here is expired. Please see the ["Near term" plan]( https://github.com/conda-forge/conda-forge.github.io/issues/426#issuecomment-321897876 ) on how to fix this.

**Comment by kwilcox** [comment]
https://github.com/conda-forge/staged-recipes/pull/3774

**Pull request merged**
